export const MODAL_LIFECYCLE = {
    LOADING: 'LOADING',
    MISSING_PROFILE: 'MISSING_PROFILE',
    SELECTING_TUTOR: 'SELECTING_TUTOR',
    DISPLAYING_MESSAGE: 'DISPLAYING_MESSAGE',
};

export const OPEN_SPOTS_LOADING_MESSAGE = 'OPEN_SPOTS_LOADING_MESSAGE';
